config/routes.rb
Rails.application.routes.draw do

  get("weather/forecast", to: "pages#forecast")
  get("dashboard", to: "pages#dashboard")

  resources(:outfits)

  devise_for(:users)
  unauthenticated do
    devise_scope(:user) do
      root("pages#landing", as: :unauthenticated_root)
    end
  end

  authenticated(:user) do
    root(to: "pages#home", as: :root)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/outfit.rb
class Outfit < ApplicationRecord
  attr_accessor :day

  belongs_to :tag
  belongs_to :user
  has_many_attached :photos, dependent: :destroy
  validates :photos, presence: true

  validates :description, length: {
    maximum: 200,
    too_long: "Maximum description length is 200 characters."
  }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :outfits, dependent: :destroy
  validates :temperature, :rain, :wind, presence: true
  validates_uniqueness_of :temperature, scope: %i[rain wind]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :outfits, dependent: :destroy
  validates :first_name, :last_name, :location, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :disable_nav, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name location])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name location])
  end

  def disable_nav
    @disable_nav = true
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  skip_before_action :authenticate_user!
  layout "devise"

  def index
  end
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  def index
    tag = generate_tag
    @outfits = current_user.outfits.where(tag_id: tag.id).order(created_at: :desc)
  end

  def show
    @page = params[:test]
    id = params[:id]
    @outfit = Outfit.find(id)
  end

  def new
    @outfit = Outfit.new
  end

  def create
    @outfit = Outfit.new(outfit_params)
    @outfit.user = current_user

    tag = generate_tag

    tag.outfits << @outfit
    if @outfit.save
      redirect_to(outfit_path(@outfit))
    else
      render(:new, status: :unprocessable_entity)
    end
  end

  def edit
    @outfit = Outfit.find(params[:id])
  end

  def update
    @outfit = Outfit.find(params[:id])
    @outfit.update(outfit_params)
    redirect_to(outfit_path)
  end

  def destroy
    page = params[:page]
    @outfit = Outfit.find(params[:id])
    @outfit.destroy
    if page == "dashboard"
      redirect_to(dashboard_path, status: :see_other)
    else
      redirect_to(outfits_path, status: :see_other)
    end
  end

  private

  def outfit_params
    # INFO: ADD PARAMS AS NEEDED, KEEP THE PHOTOS ARRAY.
    params.require(:outfit).permit(:description, photos: [])
  end

  def generate_tag
    today = Rails.cache.fetch("today", expires_in: 1.day) do
      WeatherApi.get_day(0, current_user.location)
    end

    tag_params = WeatherApi.create_tag(today)
    tag = Tag.new(tag_params)
    if tag.valid?
      tag.save
    else
      tag = Tag.where(tag_params).first
    end

    return tag
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home landing]

  def landing
    @disable_nav = true
  end

  def home
    @location = current_user.location
    if params[:location].present?
      @location = params[:location]
      current_user.location = @location.titleize
      current_user.save
    end

    @weather = Rails.cache.fetch("today", expires_in: 1.day) do
      WeatherApi.get_day(0, @location)
    end
  end

  def forecast
    @location = current_user.location
    # @forecast = WeatherApi.forecast(@location)
    @forecast = Rails.cache.fetch("forecast", expires_in: 1.day) do
      WeatherApi.forecast(@location)
    end
  end

  def dashboard
    @outfits = current_user.outfits.order(created_at: :desc)
  end

  private

  def location_params
    params.require(:location).permit(:location)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  WEATHER_CODES = {
    0 => { description: "Clear", icon: "wi-day-sunny" },
    1 => { description: "Mainly clear", icon: "wi-day-cloudy" },
    2 => { description: "Partly cloudy", icon: "wi-cloudy" },
    3 => { description: "Overcast", icon: "wi-cloudy" },
    45 => { description: "Fog", icon: "wi-fog" },
    48 => { description: "Rime fog", icon: "wi-fog" },
    51 => { description: "Light Drizzle", icon: "wi-sprinkle" },
    53 => { description: "Moderate Drizzle", icon: "wi-sprinkle" },
    55 => { description: "Heavy Drizzle", icon: "wi-sprinkle" },
    56 => { description: "Light Freezing drizzle", icon: "wi-sprinkle" },
    57 => { description: "Heavy Freezing drizzle", icon: "wi-sprinkle" },
    61 => { description: "Slight Rain", icon: "wi-rain" },
    63 => { description: "Moderate Rain", icon: "wi-rain" },
    65 => { description: "Heavy Rain", icon: "wi-rain" },
    66 => { description: "Light Freezing rain", icon: "wi-rain" },
    67 => { description: "Heavy Freezing rain", icon: "wi-rain" },
    71 => { description: "Light Snow", icon: "wi-snow" },
    73 => { description: "Moderate Snow", icon: "wi-snow" },
    75 => { description: "Heavy Snow", icon: "wi-snow" },
    77 => { description: "Snow grains", icon: "wi-snow" },
    80 => { description: "Light Rain showers", icon: "wi-showers" },
    81 => { description: "Moderate Rain showers", icon: "wi-showers" },
    82 => { description: "Heavy Rain showers", icon: "wi-showers" },
    85 => { description: "Light Snow showers", icon: "wi-snow" },
    86 => { description: "Heavy Snow showers", icon: "wi-snow" },
    95 => { description: "Thunderstorm", icon: "wi-thunderstorm" },
    96 => { description: "Thunderstorm with Light Hail", icon: "wi-thunderstorm" },
    99 => { description: "Thunderstorm with Heavy Hail", icon: "wi-thunderstorm" }
  }

  def weather_icon(weathercode)
    WEATHER_CODES[weathercode][:icon]
  end

  def weather_description(weathercode)
    WEATHER_CODES[weathercode][:description]
  end
end

app/views/home/index.html.erb
<div class="container bg-image d-flex pt-4 text-white">
  <div class="mx-auto d-flex flex-column align-items-center text-center">
    <h5 class="mb-4" style="height: 40px" data-controller="search">
      <span class="" data-search-target="location">
        <i class="fa-solid fa-location-dot mx-3"></i>
        <%= @location.titleize %>
        <i class="mx-2 fa-solid fa-pencil" data-action="click->search#toggle"></i>
      </span>
      <%= form_tag("/", method: "get", class:"d-none", "data-search-target": "form" ) do %>
        <div class="input-group mb-3">
          <%= text_field_tag(:location, @location, class:"form-control bg-transparent text-white border-0 border-bottom") %>
          <%= button_tag class: "btn btn-outlign-light" do %>
            <i class="fa-solid fa-lg fa-magnifying-glass"></i>
          <% end %>
        </div>
      <% end %>
    </h5>
    <i class="wi <%= weather_icon(@weather[:weathercode]) %> fs-1 border border-4 border-white rounded-circle p-4 m-4"></i>
    <h2><%= weather_description(@weather[:weathercode]) %></h2>
    <dl class="mt-5 fs-4">
      <dt>Wind</dt>
      <dd class="mb-3 fs-5"><%= @weather[:windspeed].round %> km/h</dd>
      <dt>Avg. Temperature</dt>
      <dd class="mb-3 fs-5"><%= @weather[:temp].round %> °C</dd>
      <dt>Rainfall</dt>
      <dd class="fs-5"><%= @weather[:precipitation].round %> mm</dd>
    </dl>
  </div>
</div>

app/views/landing/index.html.erb
<div class="container-fluid bg-image">
    <div class="text-center pt-3 m-0 pb-3"><h1>Dailyfits</h1></div>
    <div class="mb-3">
      <%= image_tag("landing.jpg", width: "100%", height: "425")%>
    </div>
    <div class="text-center mb-2">
      <p class="m-0">What to wear?</p>
      <p class="m-0">Be your own advisor!</p>
    </div>
    <div class="d-flex justify-content-around mb-5 p-4">
      <a class="btn light text-white" href="/users/sign_in">Login</a>
      <a class="btn light text-white" href="/users/sign_up">Signup</a>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dailyfits</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main class="bg-image overflow-y-scroll">
      <%= yield %>
    </main>
    <%= render "shared/navbar" unless @disable_nav %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dailyfits</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main class="bg-image">
      <%= render "shared/flashes" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/outfits/index.html.erb
<div class="container-fluid">
  <div class="pt-5 mb-4 d-flex align-items-center justify-content-between">
    <div class="d-flex align-items-center justify-content-around mx-4">
      <i class="pe-2 pt-0 fa-solid fa-lg fa-location-dot" style="color: #ffffff;"></i>
      <p class="mb-0"><%= current_user.location %></p>
    </div>
    <div class="d-flex justify-content-around mx-4">
      <i class="pe-5 fa-solid fa-lg fa-calendar" style="color: #ffffff;"></i>
      <i class="fa-solid fa-lg fa-magnifying-glass" style="color: #ffffff;"></i>
    </div>
  </div>
  <h6>Your top choices for today</h6>
  <%= render partial: 'shared/outfits', object: @outfits %>
</div>

app/views/outfits/new.html.erb
<div class="container py-3">
  <h2 class="mb-3">Create a new Outfit</h2>
  <%= simple_form_for @outfit do |f| %>
    <%= f.input :photos,
            as: :file,
            input_html: {multiple: true, class: 'mb-3 d-none'},
            label_html: {class: 'btn light sm-font mt-3' }, label: 'Choose photos' %>
    <%= f.input :description,
            input_html: {class: 'bg-transparent border-0 border-bottom text-white'} %>
    <%= f.submit "Upload", class: 'btn light text-white mt-3' %>
  <% end %>
</div>

app/views/outfits/show.html.erb
<div data-controller="edit-outfits">
  <div class="container outfitShow" style="padding-left: 0px; padding-right: 0px; padding-top: 25px">
    <div class="d-flex justify-content-between" id="fixedDiv">
      <div class="ps-2">
        <%= link_to :back do %>
          <i class="fa-solid fa-xl fa-chevron-left" style="color: #ffffff;"></i>
        <% end %>
      </div>
      <div class="d-flex justify-content-between">
        <div class="me-4 d-flex d-none" data-edit-outfits-target="buttonlists">
          <div class="me-4">
            <%= link_to "delete", outfit_path(@outfit, page: @page), class:"btn light text-white sm-font", data: {turbo_method: :delete,turbo_confirm: "Are you sure?"} %>
          </div>
          <div class="" data-edit-outfits-target="editbutton" data-action="click->edit-outfits#edit">
            <button class="btn light text-white sm-font">edit</button>
          </div>
        </div>
        <div class="pe-4" data-edit-outfits-target="togglebutton" data-action="click->edit-outfits#toggle">
          <i class="fas fa-ellipsis-h fa-xl mb-0" style="color: #ffffff;"></i>
        </div>
      </div>
    </div>
    <div id="outfitCarousel" class="carousel slide bg-white" data-ride="carousel">
      <div class="carousel-inner">
        <% @outfit.photos.each_with_index do |photo, index| %>
          <div class="carousel-item <%= "active" if index == 0 %> square-container"
            style="background-image: url('<%= cl_image_path photo.key %>');">
          </div>
        <% end %>
      </div>
      <% if @outfit.photos.count > 1 %>
        <button class="carousel-control-prev" type="button" data-bs-target="#outfitCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#outfitCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      <% end %>
    </div>
    <div id="details" class="text-justify pt-1" style="padding-left: 20px">
      <p class="ps-1 mt-2" data-edit-outfits-target="text"><small class="sm-font"><%= @outfit.description.present? ? @outfit.description : "No description given yet..."%></small></p>
      <%= simple_form_for @outfit , html: {class: "ps-0 d-none d-flex justify-content-between align-items-center sm-font", data:{ edit_outfits_target: "form"}} do |f| %>
        <%= f.input :description, label: false,
                input_html: {class: 'ps-0 bg-transparent border-0 border-bottom text-white mb-0 sm-font', style: 'padding-left: 0px; height: 30px;'} %>
        <%= f.submit "update", class: 'ps-1 btn light text-white sm-font mb-0 me-5',
        style: "padding-top: 5px;
            padding-bottom: 5px;
            padding-left: 5px;
            padding-right: 5px;" %>
      <% end %>
    </div>
    <div id="tag-display"  class="d-flex justify-content-between" style="padding-left: 10px; padding-right: 10px; padding-top: 5px">
      <h4 class="btn border light text-white align-text-center sm-font"><%= @outfit.tag.temperature %></h4>
      <h4 class="btn border light text-white align-text-center sm-font"><%= @outfit.tag.wind %> wind</h4>
      <h4 class="btn border light text-white align-text-center sm-font"><%= @outfit.tag.rain %> rain</h4>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="d-flex justify-content-around">
  <div class="pt-3 mt-3 ms-2">
    <%= image_tag "daniele.jpg", class:"avatar-large" %>
    <p class="mb-2 my-0 ps-3 pt-4"><%= current_user.first_name %></p>
  </div>
  <div class="d-flex flex-column mt-2 mb-2 me-3 justify-content-center">
    <%= link_to "Edit Profile", edit_user_registration_path, class:"btn light text-white mb-2 pt-1 pb-1"%>
    <%= link_to "Logout", destroy_user_session_path, class:"btn light text-white mb-2 pt-1 pb-1", data: {turbo_method: :delete} %>
  </div>
</div>
<div class="d-flex mt-4 mb-0 ps-4">
  <div class="my-0 py-0 pb-0 pe-4">
    <i class="fa-solid fa-gear fa-lg" style="color: #ffffff;"></i>
  </div>
  <p class="my-0">My Outfits</p>
</div>
<hr class="mt-1">
<div class="mt-2">
  <%= render partial: 'shared/outfits', object: @outfits %>
</div>

app/views/pages/forecast.html.erb
<div class="container d-flex pt-4 text-white">
  <div class="mx-auto d-flex flex-column align-items-center">
    <h5 class="position-relative mb-4"><i class="position-absolute -start-3 fa-solid fa-location-dot mx-3"></i><%= current_user.location.titleize %></h5>
    <i class="wi <%= weather_icon(@forecast[:weathercode][1]) %> fs-1 border border-4 border-white rounded-circle p-4 m-4"></i>
    <p>Tomorrow</p>
    <h2><%= weather_description(@forecast[:weathercode][1]) %>, <%= @forecast[:temp][1].round %> °C</h2>
    <div class="mt-5 fs-4">
      <% (2..6).each do |i| %>
        <div class="row py-1 mb-3">
          <div class="col-4 justify-content-start" style="padding-left: 0px;margin-left: 0px;">
            <%= @forecast[:days][i].to_date.strftime("%a") %>
          </div>
          <div class="col-3">
            <i class="wi <%= weather_icon(@forecast[:weathercode][i]) %> fs-1 pe-5 ps-1"></i>
          </div>
          <div class="col-5" style="padding-left: 45px;padding-right: 0px;">
            <%= @forecast[:temp][i].round %> °C
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container d-flex pt-4 text-white">
  <div class="mx-auto d-flex flex-column align-items-center text-center">
    <h5 class="mb-4" style="height: 40px" data-controller="search">
      <span class="" data-search-target="location">
        <i class="fa-solid fa-location-dot mx-3"></i>
        <%= @location.titleize %>
        <i class="mx-2 fa-solid fa-pencil" data-action="click->search#toggle"></i>
      </span>
      <%= form_tag("/", method: "get", class:"d-none", "data-search-target": "form" ) do %>
        <div class="input-group mb-3">
          <%= text_field_tag(:location, @location, class:"form-control bg-transparent text-white border-0 border-bottom") %>
          <%= button_tag class: "btn btn-outlign-light" do %>
            <i class="fa-solid fa-lg fa-magnifying-glass"></i>
          <% end %>
        </div>
      <% end %>
    </h5>
    <i class="wi <%= weather_icon(@weather[:weathercode]) %> fs-1 border border-4 border-white rounded-circle p-4 m-4"></i>
    <h2><%= weather_description(@weather[:weathercode]) %></h2>
    <dl class="mt-5 fs-4">
      <dt>Wind</dt>
      <dd class="mb-3 fs-5"><%= @weather[:windspeed].round %> km/h</dd>
      <dt>Avg. Temperature</dt>
      <dd class="mb-3 fs-5"><%= @weather[:temp].round %> °C</dd>
      <dt>Rainfall</dt>
      <dd class="fs-5"><%= @weather[:precipitation].round %> mm</dd>
    </dl>
  </div>
</div>

app/views/pages/landing.html.erb
<div class="container-fluid" data-controller="landing">
  <div class="text-center pt-3 mt-2 pb-3">
    <h1>Dailyfits</h1>
  </div>
  <div>
    <%= image_tag "landingimage1.jpg",
         data: { landing_target: "image" },
         width: "100%", height: "400",
         style: "object-fit: contain;"%>
  </div>
  <div class="text-center mb-4 mt-0">
    <p class="m-0">What to wear?</p>
    <p class="m-0">Be your own advisor!</p>
  </div>
  <div class="d-flex justify-content-around mb-5 p-4 justify-content-md-center">
    <a class="btn light text-white" href="/users/sign_in" style="margin-right: 45px;">Login</a>
    <a class="btn light text-white" href="/users/sign_up" style="margin-left: 45px;" >Signup</a>
  </div>
</div>

app/views/pages/today.html.erb
<h1>Today Page</h1>
<p>Find me in app/views/pages/today.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon fixed-bottom border-top px-md-5">
  <div class="container-fluid">
    <%= link_to root_path do %>
      <i class="fa-solid fa-house fa-xl "></i>
    <% end %>
    <%= link_to weather_forecast_path do %>
      <i class="fa-solid fa-cloud fa-xl"></i>
    <% end %>
    <%= link_to new_outfit_path do %>
      <label for="camera" data-controller="upload-image">
        <span class="camera-btn btn">
          <i class="fa-solid fa-plus fa-2xl"></i>
        </span>
      <% end %>
    </label>
    <%= link_to outfits_path do %>
      <i class="fa-solid fa-shirt fa-xl"></i>
    <% end %>
    <%= link_to dashboard_path do %>
      <i class="fa-solid fa-user fa-xl"></i>
    <% end %>
  </div>
</div>

app/views/shared/_outfitlarge.html.erb
<%= link_to outfit_path(outfit, page: params[:action]), class:"text-decoration-none" do %>
  <div class="pb-3">
    <%= cl_image_tag outfit.photos.first.key, crop: :fill, class: "card image2" %>
  </div>
<% end %>

app/views/shared/_outfits.html.erb
<div class="d-flex justify-content-around ps-3 pe-3">
  <div class="d-flex flex-column">
    <% @outfits.first(@outfits.count/2).each do |outfit| %>
      <% if outfit == @outfits.first(@outfits.count/2).first %>
        <%= render partial: 'shared/outfitsmall', locals: { outfit: outfit } %>
      <% else %>
        <%= render partial: 'shared/outfitlarge', locals: { outfit: outfit } %>
      <% end %>
    <% end %>
  </div>
  <div class="d-flex flex-column">
    <% @outfits.last(@outfits.count-@outfits.count/2).each do |outfit| %>
      <% if outfit == @outfits.last(@outfits.count-@outfits.count/2).last %>
        <%= render partial: 'shared/outfitsmall', locals: { outfit: outfit } %>
      <% else %>
        <%= render partial: 'shared/outfitlarge', locals: { outfit: outfit } %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_outfitsmall.html.erb
<%= link_to outfit_path(outfit.id, test: params[:action]), class:"text-decoration-none" do %>
  <div class="pb-3">
    <%= cl_image_tag outfit.photos.first.key , class: "card image1" %>
  </div>
<% end %>